name: CD
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: CD Simulator
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: |
            '**.py'
            README.md
            requirements.txt
            .gitignore

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: project
      - name: Display structure of download files
        run: ls -R


        



