name: CD
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: CD Simulator
        uses: actions/upload-artifact@v4
        with:
          name: project
          path:
            '**.py'
            README.md
            requirements.txt
            .gitignore

        



